version: '2'
services:
  bundle:
    image: busybox
    volumes:
      - /bundle
  web:
    build: .
    command: rackup --host 0.0.0.0
    volumes:
      - .:/myapp
      - type: bind
        source: /private/tmp/com.apple.launchd.VF1AqNGHEp/Listeners
        target: /run/host-services/ssh-auth.sock
    environment:
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    volumes_from:
      - bundle
    ports:
      - "9292:9292"
    stdin_open: true
    tty: true
